parameters:
  platform: ''

steps:
- template: ${{parameters.platform}}.yml
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(Build.ArtifactStagingDirectory)
    publishLocation: 'pipeline'
  displayName: 'Publishing artifacts to artifact storage'
