parameters:
  platform: ''

steps:
- template: ${{parameters.platform}}.yml
- bash: |
    cp release/latest* "$(Build.ArtifactStagingDirectory)"
- publish: $(Build.ArtifactStagingDirectory)
  displayName: 'Publishing artifacts to artifact storage'
