name: Publish nRF Connect for Desktop

inputs:
    suffix:
        type: string
        required: true

runs:
    using: 'composite'
    steps:
        - name: Move Changelog.md into release/
          shell: bash
          run: cp ./Changelog.md ./release/
        - name: List files
          shell: bash
          run: ls release
        - name: Publish built artifact
          uses: actions/upload-artifact@v4
          with:
              name: nrfconnect-${{ inputs.suffix}}
              path: |
                  release/nrfconnect*
                  release/latest*
                  release/Changelog.md
              retention-days: 7
