parameters:
  platform: ''

steps:
- template: prepare.yml
  parameters: ${{parameters}}
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    restoreKeys: |
       npm | "$(Agent.OS)"
    path: $(npm_config_cache)
  displayName: Cache npm
- bash: npm ci
  displayName: 'Install dependencies'
- bash: npm run check
  displayName: 'Check'
- bash: npm run build:prod
  displayName: 'Build'
- bash: npm test
  displayName: 'Test'    
