parameters:
  - name: platform
    type: string
  - name: pool
    type: 'object'
    default: {}

jobs: 
  - job: ${{ format('Build_{0}', parameters.platform) }}
    displayName: ${{ format('Build {0}', parameters.platform) }}
    condition: ne(variables['Build.Reason'], 'PullRequest')
    pool: ${{parameters.pool}}
    variables:
      group: wayland
    steps:
    - template: ./build.yml
      parameters: ${{ parameters }}
    - template: package/package.yml
      parameters: ${{parameters}}

