parameters:
  - name: platform
    type: string
  - name: pool
    type: 'object'
    default: {}

jobs: 
  - job: Build_${{parameters.platform}}
    displayName: Build ${{ parameters.platform }}
    pool: ${{parameters.pool}}
    variables:
      group: wayland
    steps:
    - template: ./build.yml
      parameters: ${{ parameters }}
    - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
      - template: package/package.yml
        parameters: ${{parameters}}

