name: Build nRF Connect for Desktop for Darwin ARM64

on:
    workflow_call:
        inputs:
            runner:
                required: true
                type: string # [Windows, macOS, Linux]
            electronArgument:
                required: true
                type: string # e.g. --windows nsis:x64

jobs:
    build:
        runs-on: ${{ fromJSON(inputs.runner) }}
        steps:
            - uses: actions/checkout@v4
            - name: Build
              uses: ./.github/actions/build-action

            - name: Fetch certificate file
              shell: bash
              env:
                  NORDIC_SIGNING_CERTIFICATE:
                      ${{ secrets.NORDIC_SIGNING_CERTIFICATE_PFX }}
              run:
                  echo "$NORDIC_SIGNING_CERTIFICATE" | base64 --decode >
                  ./nordic_signing_certificate.pfx

            - name: Run Electron Builder
              env:
                  CSC_LINK: ./nordic_signing_certificate.pfx
                  CSC_KEY_PASSWORD:
                      ${{ secrets.NORDIC_SIGNING_CERTIFICATE_PFX_PASS }}
              run: npx electron-builder -p never ${{ inputs.electronArgument }}

            - name: Publish built artifact
              uses: actions/upload-artifact@v3
              with:
                  name: nRF Connect for Desktop win32
                  path: 'release/nrfconnect*'
                  retention-days: 7
