name: Build for macOS x64

on:
    workflow_dispatch:
    workflow_call:

jobs:
    build:
        runs-on: macos-13
        steps:
            - uses: actions/checkout@v4
            - name: Build
              uses: ./.github/actions/build-action

            - name: Fetch certificate file
              env:
                  NORDIC_SIGNING_CERTIFICATE:
                      ${{ secrets.NORDIC_SIGNING_CERTIFICATE_P12 }}
              run:
                  echo "$NORDIC_SIGNING_CERTIFICATE" | base64 --decode >
                  ./nordic_signing_certificate.p12
              if: github.event_name != 'pull_request'

            - name: Run Electron Builder
              env:
                  CSC_LINK: ./nordic_signing_certificate.p12
                  CSC_KEY_PASSWORD:
                      ${{ secrets.NORDIC_SIGNING_CERTIFICATE_P12_PASS }}
                  APPLE_ID: ${{ secrets.WAYLAND_APPLE_ID }}
                  APPLE_APP_SPECIFIC_PASSWORD:
                      ${{ secrets.WAYLAND_APPLE_APP_SPECIFIC_PASS }}
                  APPLE_TEAM_ID: ${{ secrets.WAYLAND_APPLE_TEAMID }}
              run: npx electron-builder -p never --x64
              if: github.event_name != 'pull_request'

            - name: Upload
              uses: ./.github/actions/publish-action
              with:
                  suffix: macOS-x64
              if: github.event_name != 'pull_request'
