name: Build for Windows x64

on:
    workflow_dispatch:
        inputs:
            ref:
                description:
                    Ref (Tag, branch, commit SHA) to release. Default to the
                    main branch.
                type: string
    workflow_call:
        inputs:
            ref:
                description: Ref to build from
                type: string

jobs:
    build:
        name: Build Windows
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ inputs.ref }}

            - name: Set variables
              shell: bash
              run: |
                  echo "AZURE_TENANT_ID=${{ secrets.NORDIC_AZURE_TENANT_ID }}" >> "$GITHUB_ENV"
                  echo "AZURE_CLIENT_ID=${{ secrets.NORDIC_AZURE_CLIENT_ID }}" >> "$GITHUB_ENV"
                  echo "AZURE_CLIENT_SECRET=${{ secrets.NORDIC_AZURE_CLIENT_SECRET }}" >> "$GITHUB_ENV"
              if: ${{ github.event_name != 'pull_request' }}

            - name: Build
              uses: ./.github/actions/build-action

            - name: Run Electron Builder
              run: |
                  npx electron-builder -p never --windows nsis:x64
              if: github.event_name != 'pull_request'

            - name: Upload
              uses: ./.github/actions/publish-action
              with:
                  suffix: windows-x64
              if: github.event_name != 'pull_request'
