name: Build nRF Connect for Desktop for Darwin x64

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
            - test/github-actions

jobs:
    build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build
              uses: ./.github/actions/build-action

            - name: Fetch certificate file
              env:
                  NORDIC_SIGNING_CERTIFICATE:
                      ${{ secrets.NORDIC_SIGNING_CERTIFICATE_P12 }}
              run:
                  echo "$NORDIC_SIGNING_CERTIFICATE" | base64 --decode >
                  ./nordic_signing_certificate.p12

            - name: Run Electron Builder
              env:
                  CSC_LINK: ./nordic_signing_certificate.p12
                  CSC_KEY_PASSWORD: ''
                  APPLE_ID: ${{ secrets.WAYLAND_APPLE_ID }}
                  APPLE_ID_PASS: ${{ secrets.WAYLAND_APPLE_APP_SPECIFIC_PASS }}
                  APPLE_TEAMID: ${{ secrets.WAYLAND_APPLE_TEAMID }}
              run: npx electron-builder -p never --x64

            - name: Upload
              uses: ./.github/actions/publish-action
              with:
                  suffix: for macOS x64
