name: Build nRF Connect for Desktop for macOS arm64

on:
    workflow_dispatch:
        inputs:
    workflow_call:

jobs:
    build:
        runs-on: [self-hosted, macOS, ARM64]
        steps:
            - uses: actions/checkout@v4
            - name: Build
              uses: ./.github/actions/build-action

            - name: Fetch certificate file
              env:
                  NORDIC_SIGNING_CERTIFICATE:
                      ${{ secrets.NORDIC_SIGNING_CERTIFICATE_P12 }}
              run:
                  echo "$NORDIC_SIGNING_CERTIFICATE" | base64 --decode >
                  ./nordic_signing_certificate.p12
              if: github.event_name != 'pull_request'

            - name: Run Electron Builder
              env:
                  CSC_LINK: ./nordic_signing_certificate.p12
                  CSC_KEY_PASSWORD: ''
                  APPLE_ID: ${{ secrets.WAYLAND_APPLE_ID }}
                  APPLE_ID_PASS: ${{ secrets.WAYLAND_APPLE_APP_SPECIFIC_PASS }}
                  APPLE_TEAMID: ${{ secrets.WAYLAND_APPLE_TEAMID }}
              run: npx electron-builder -p never --arm64
              if: github.event_name != 'pull_request'

            - name: Rename latest-mac.yml
              run: |
                  cd release
                  mv latest-mac.yml latest-mac-arm64.yml
              if: github.event_name != 'pull_request'

            - name: Upload
              uses: ./.github/actions/publish-action
              with:
                  suffix: macOS-arm64
              if: github.event_name != 'pull_request'
