name: Build nRF Connect for Desktop for Darwin ARM64

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string # [Windows, macOS, Linux]
      electronArgument:
        required: true
        type: string # e.g. --windows nsis:x64

jobs:
  build:
    runs-on: ${{ fromJSON(inputs.runner) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
      - name: Run all checks
        run: npm run check
      - name: Run Tests
        run: npm test
      - name: Build for Production
        run: npm run build:prod

      - name: Fetch certificate file
        env:
          NORDIC_SIGNING_CERTIFICATE: ${{ secrets.NORDIC_SIGNING_CERTIFICATE }}
        run: echo "$NORDIC_SIGNING_CERTIFICATE" | base64 --decode > ./nordic_signing_certificate.p12

      - name: Run Electron Builder
        env:
          CSC_LINK: ./nordic_signing_certificate.p12
          CSC_KEY_PASSWORD: ${{ secrets.NORDIC_SIGNING_CERTIFICATE_PASSWORD_P12 }}
          APPLE_ID: ${{ secrets.WAYLAND_APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.WAYLAND_APPLE_ID_PASS }}
          APPLE_TEAMID: ${{ secrets.WAYLAND_APPLE_TEAMID }}
        run: npx electron-builder -p never ${{ inputs.electronArgument }}

      - name: Publish built artifact
        uses: actions/upload-artifact@v3
        with:
          name: nRF Connect for Desktop
          path: "release/nrfconnect*"
          retention-days: 7
