name: Continue RC release

on:
    workflow_dispatch:
        inputs:
            tag:
                description: Tag of the release to continue.
                type: string

jobs:
    check-version:
        name: Check version and existence
        runs-on: ubuntu-latest
        steps:
            - name: Check version and existence
              id: check
              env:
                  GH_TOKEN: ${{ github.token }}
                  TAG: ${{ github.event.inputs.tag }}
              run: |
                  if [[ "$TAG" != *-rc* ]]; then
                      echo "::error::Not running because $TAG is not a release candidate version"
                      exit 1
                  fi

                  if ! gh release view "$TAG" --repo nordicsemiconductor/pc-nrfconnect-launcher >/dev/null 2>&1; then
                      echo "::error::Not running because there is no GitHub release with the tag $TAG prepared yet"
                      exit 1
                  fi

    continue-release:
        name: Continue RC release
        needs: check-version
        uses: ./.github/workflows/continue-release-common.yml
        with:
            release-type: rc
            tag: ${{ github.event.inputs.tag }}
        secrets: inherit
