name: Check labels

on:
    pull_request:
        types:
            - opened
            - labeled
            - unlabeled
            - synchronize

jobs:
    check_labels:
        uses: NordicSemiconductor/pc-nrfconnect-shared/.github/workflows/labels.yml@main
        secrets: inherit
