name: Check labels

on:
    pull_request:
        types:
            - opened
            - labeled
            - unlabeled
            - synchronize
        branches:
            - main

jobs:
    check_labels:
        runs-on: ubuntu-latest
        steps:
          - name: 'Required "doc required" or "doc not required" label'
            if: >
                contains(github.event.pull_request.labels.*.name, 'doc required') == false &&
                contains(github.event.pull_request.labels.*.name, 'doc not required') == false
            run: echo "missing_label=true" >> "$GITHUB_ENV"

          - name: 'Check if already commented'
            if: env.missing_label == 'true'
            uses: peter-evans/find-comment@v2
            id: fc
            with:
                issue-number: ${{ github.event.pull_request.number }}
                body-includes: 'Make sure to add the "doc required" or "doc not required" label.'

          - name: 'Create comment'
            uses: actions/github-script@v7
            if: env.missing_label == 'true' && steps.fc.outputs.comment-id == 0
            with:
              script: |
                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: 'Make sure to add the "doc required" or "doc not required" label.'
                })

          - name: 'Fail'
            uses: actions/github-script@v7
            if: env.missing_label == 'true'
            with:
              script: core.setFailed('Required "doc required" or "doc not required" label')
