name: Check labels

on:
    pull_request:
        branches:
            - main

jobs:
    check_labels:
        runs-on: ubuntu-latest
        steps:
          - name: 'Required "doc_required" or "doc_not_required" label'
            if: >
                contains(github.event.pull_request.labels.*.name, 'doc required') == false &&
                contains(github.event.pull_request.labels.*.name, 'doc not required') == false
            run: exit 1




