name: Build nRF Connect for Desktop

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release:
        description: Run Release Workflow
        required: true
        default: false
        type: boolean
      prerelease:
        description: Make the release a pre-release
        required: true
        default: true
        type: boolean
      draft:
        description: Create draft release
        required: true
        default: true
        type: boolean
  

jobs:
  build_on_windows:
    uses: ./.github/workflows/build.yml
    with:
      runner: windows-latest
      electronArgument: --windows nsis:x64
  build_on_ubuntu:
    uses: ./.github/workflows/build.yml
    with:
      runner: ubuntu-latest
      electronArgument: ''
  release:
    if: github.event_name == 'workflow_dispatch' && inputs.release
    needs: [ build_on_windows, build_on_ubuntu ]
    uses: ./.github/workflows/release.yml
    with:
      prerelease: ${{ inputs.prerelease }}
      draft: ${{ inputs.draft }}


      # build_on_mac_intel:
      #   uses: ./.github/workflows/build.yml
      #   with:
      #       runner: macos-latest
      #       electronArgument: --x64
      # build_on_mac_apple_silicon:
      #   uses: ./.github/workflows/build.yml
      #   with:
      #     runner: macos-latest-xlarge
      # electronArgument:
