name: Build nRF Connect for Desktop

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    # build_on_windows:
    #     uses: ./.github/workflows/build/build_win.yml
    #     with:
    #         runner: "['windows-latest']"
    #         electronArgument: --windows nsis:x64
    #     secrets: inherit
    # build_on_ubuntu:
    #     uses: ./.github/workflows/build_linux.yml
    #     with:
    #         runner: "['ubuntu-latest']"
    #         electronArgument: --x64
    #     secrets: inherit
    # build_on_mac_intel:
    #     uses: ./.github/workflows/build/build_darwin.yml
    #     with:
    #         runner: "['macos-latest']"
    #         electronArgument: --x64
    #     secrets: inherit
    # build_on_mac_apple_silicon:
    #     uses: ./.github/workflows/build/build_darwin.yml
    #     with:
    #         runner: "['self-hosted', 'macOS', 'ARM64']"
    #         electronArgument: --arm64
    #     secrets: inherit
