name: Common release jobs

on:
    workflow_call:
        inputs:
            ref:
                description: Ref to build from
                type: string
            release-type:
                description: Type of release (production or rc)
                required: true
                type: string
            tag:
                description: The release tag to use
                required: true
                type: string

jobs:
    check-type:
        name: Check release type
        runs-on: ubuntu-latest
        steps:
            - name: Check release type
              run: |
                  if [ "${{ inputs.release-type }}" != rc ] && [ "${{ inputs.release-type }}" != production ]; then
                      echo "::error::release-type must be either rc or production"
                      exit 1
                  fi

    build:
        name: Build
        needs: check-type
        uses: ./.github/workflows/build.yml
        with:
            ref: ${{ inputs.ref }}
        secrets: inherit

    create-release:
        name:
            Create ${{ inputs.release-type == 'rc' && 'RC' || 'production
            release' }}
        needs: build
        runs-on: ubuntu-latest
        env:
            TAG: ${{ inputs.tag }}
            CHANNEL: ${{ inputs.release-type == 'rc' && 'rc' || 'latest' }}
        steps:
            - name: Download all artifacts
              env:
                  GH_TOKEN: ${{ github.token }}
              run: |
                  gh run download --repo nordicsemiconductor/pc-nrfconnect-launcher

            - name: Merge *-mac.yml
              run: |
                  yq '. *=+ load("nrfconnect-macOS-x64/${{env.CHANNEL}}-mac.yml")' "nrfconnect-macOS-arm64/$CHANNEL-mac.yml" > "$CHANNEL-mac.yml"
                  rm "nrfconnect-macOS-arm64/$CHANNEL-mac.yml" "nrfconnect-macOS-x64/$CHANNEL-mac.yml"
                  mv "$CHANNEL-mac.yml" "nrfconnect-macOS-arm64/$CHANNEL-mac.yml"

            - name: Collect release files
              run: |
                  mkdir "$TAG"
                  cp nrfconnect-windows-x64/changelog.md \
                      nrfconnect-*/*.AppImage \
                      nrfconnect-*/*.exe \
                      nrfconnect-*/*.dmg \
                      nrfconnect-*/*.zip \
                      nrfconnect-*/"$CHANNEL"*.yml \
                      "$TAG"

            - name: Create GitHub Release
              env:
                  GH_TOKEN: ${{ github.token }}
              run: |
                  gh release create "$TAG" \
                    --repo nordicsemiconductor/pc-nrfconnect-launcher \
                    --draft \
                    --title "$TAG" \
                    --notes-file "$TAG/changelog.md" \
                    ${{ inputs.release-type == 'rc' && '--prerelease' || '' }} \
                    "$TAG"/*
