name: Release

on:
    workflow_dispatch:

jobs:
    release:
        runs-on: ['ubuntu-latest']
        steps:
            - uses: jfrog/setup-jfrog-cli@v4
              env:
                  JF_URL: https://files.nordicsemi.com/
                  JF_ACCESS_TOKEN:
                      ${{ secrets.COM_NORDICSEMI_FILES_PASSWORD_SWTOOLS_FRONTEND
                      }}
            - run: |
                  jf rt copy --flat swtools/external/ncd/launcher/v5.2.0/ web-assets-com_nordicsemi/external/swtools/ncd/launcher/v5.2.0/
                  jf rt copy --flat 'swtools/external/ncd/launcher/latest*' web-assets-com_nordicsemi/external/swtools/ncd/launcher/
