name: Create Zoomin bundle

on:
  pull_request:
    types: [synchronize, opened, reopened]
    paths:
      - '.github/workflows/zoomin.yml'
  workflow_dispatch:
  workflow_call:

jobs:
  create-zoomin-bundle:
    name: Create Zoomin bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Copy zoomin properties
        run: |
          cp doc/zoomin/custom.properties doc/ \
          && cp doc/zoomin/tags.yml doc/

      - name: Create zip file
        run: |
          cd doc/ \
          && zip -r ../nrf-connect-desktop.zip \
          docs/* mkdocs.yml custom.properties tags.yml

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: nrf-connect-desktop
          path: nrf-connect-desktop.zip
          retention-days: 7
